version: "3.8"

services:
  frontend-apollo:
    build:
      context: .
      dockerfile: Dockerfile
      # Force rebuild without cache
      args:
        - BUILDKIT_INLINE_CACHE=1
        - BUILD_DATE=${BUILD_DATE:-}
        - GIT_COMMIT=${GIT_COMMIT:-}
        - VITE_APP_SSL=${VITE_APP_SSL:-false}
        - VITE_APP_PORT=${VITE_APP_PORT:-9000}
        - VITE_APP_API_SERVER=${VITE_APP_API_SERVER:-91.107.181.185:8090}
        - VITE_APP_AUTHENTICATION_API_SERVER=${VITE_APP_AUTHENTICATION_API_SERVER:-91.107.181.185:8080}
        - VITE_APP_FILE_SERVER=${VITE_APP_FILE_SERVER:-91.107.181.185:8007}
        - VITE_APP_STATIC_SERVER=${VITE_APP_STATIC_SERVER:-91.107.181.185:8090}
    container_name: frontend-apollo
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - apollo-network

networks:
  apollo-network:
    driver: bridge
