version: '3.8'

services:
  frontend-apollo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-apollo
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - apollo-network

networks:
  apollo-network:
    driver: bridge
