version: '3.8'

services:
  frontend-apollo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-apollo
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_APP_API_SERVER=apollo.raintech.it:3000
      - VITE_APP_AUTHENTICATION_API_SERVER=apollo.raintech.it:3000
      - VITE_APP_FILE_SERVER=apollo.raintech.it:3000
      - VITE_APP_STATIC_SERVER=apollo.raintech.it:3000
      - VITE_APP_SSL=false
    networks:
      - apollo-network

networks:
  apollo-network:
    driver: bridge
