export default {
  login: "Login",
  emailOrPhoneNumber: "Email or Phone Number",
  loginWithGoogle: "Login with Google",
  needToCreateAnAccount: "Need to create an account?",
  signUp: "Sign Up",
  password: "Password",
  register: "Register",
  rememberMe: "Remember me",
  forgetPassword: "Forget Password?",
  enterWithOtp: "Enter with OTP",
  youLoginSuccessfully: "You Login Successfully!",
  otpCode: "OTP Code",
  sendRecoveryLink: 'Send recovery link',
  otp: "OTP",
  enterWithPassword: "Enter with password",
  mobile: "Mobile",
  name: "Name",
  email: "Email",
  releaseTitle: "Apollo updates 🚀",
  termsAndConditions: "Terms and conditions ",
  passwordRecovery: 'Password recovery',
  authToastTitle: "User not found! Please register.",
  iHaveReadAndAccept: "I have read and accept.",
  haveYouAlreadyRegistered: "Have you already registered?",
  youRegisterSuccessfully: "you Registered Successfully!",
  receiveVerificationCodeAgain: "Receive verification code again ({{time}})",
  clickOnTheReceivedLinkToContinue: "Click on the received link to continue.",
  AMessageContainingAnActivationLinkWasSent:
    "A message containing an activation link was sent.",
  confirmPassword: "Confirm password",
  authToastDescription:
    "If you have already registered, double-check the information you entered.",
};
