export default {
  400: 'Bad request',
  401: 'Unauthorized',
  500: "Server error",

  PASSWORD_IS_WRONG: "Password is wrong !",
  PACKAGE_ID_IS_REQUIRED: "Package id is required !",
  ACCOUNT_NOT_FOUND: "Account not found !",
  USER_ALREADY_EXIST: "Account already exist",
  USER_ACCOUNT_IS_REQUIRED: "User account is required !",
  EMAIL_IS_REQUIRED: "Email is required !",
  USER_NOT_FOUND: "User not found !",
  CODE_IS_NOT_FOUND: "Code is not found !",
  EMAIL_NOT_SEND: "Email not send !",
  OTP_NOT_FOUND: "OTP not found !",
  TOKEN_IS_NOT_CORRECT: "Token is not correct !",
  EMAIL_OR_PHONE_NUMBER_IS_NOT_CORRECT: "Email or phone number is not correct !",
  CODE_IS_EXPIRED: "Code is expired !",
  CODE_IS_NOT_CORRECT: "Code is not correct !",
  USER_IS_SUSPENDED: 'User is suspended !',
  THIS_EMAIL_IS_ALREADY_USED: "This email has already been used !",
  THIS_PHONE_NUMBER_IS_ALREADY_USED: "This phone number has already been used !",

  unhandled: "Unhandled error !",
} as const;
