export default {
  activateAndUseOtherTemplates: "Activate and use other templates",
  addReqStepperDescription:
    "Enter user information, expert case details, and requested items. Finally, the created request link will be sent to the user.",
  archive: "Archive",
  availableTemplates: "Available templates",
  branch: "Branch",
  carGroup: "Car group",
  casesDetail: "Requested items details",
  chooseWayToSend: "Choose sending method",
  createRequest: "Create request",
  createReviewRequest: "Create expert review request",
  createReviewRequestDescription:
    "Or form link to send information for online visit",
  currentCases: "Current cases",
  deleteTemplate: "Delete template",
  finalCheck: "Final check",
  linkData: "Link contents",
  management: "Management",
  newTemplate: "New template",
  noRequestFound: "No request found.",
  orderNumber: "Order number",
  orderNumberPlaceholder: "Reference code or order number",
  request: "Request",
  requestDetail: "Request details",
  requests: "Requests",
  requestsManagement: "Requests Management",
  requestsPageDescription: "View and manage the list of online visit requests",
  requestSummary: "Request summary",
  reviewType: "Review template",
  sendToArchive: "Send to archive",
  specialist: "Specialist",
  stepsToCreateReviewLink: "Steps to create review link",
  tag: "Tag",
  templateDetails: "Template contents",
  templateName: "Template title",
  templates: "Templates",
  userAndExpertCaseInformation: "User and expert case information",
  userNamePlaceholder: "Full name, like John Smith",
  vehicleModel: "Vehicle model",
  vinNumber: "VIN number",
  vinNumberPlaceholder: "17-digit vehicle identification number",
  wantedItem: "wanted item",
  wantedItemTitle: "Requested item title",
  wantedRequests: "Requested items",
};
