export default {
  activateAndUseOtherTemplates: "فعال‌سازی و استفاده از سایر قالب‌ها",
  addReqStepperDescription:
    "اطلاعات کاربر، مورد کارشناسی و جزئیات موارد درخواستی را وارد کنید. در انتها لینک درخواست ایجاد شده و برای کاربر ارسال می‌شود.",
  archive: "بایگانی",
  availableTemplates: "تمپلیت‌های موجود",
  branch: "نمایندگی",
  carGroup: "گروه خودرو",
  casesDetail: "جزئیات موارد درخواستی",
  chooseWayToSend: "انتخاب نحوه ارسال",
  createRequest: "ایجاد درخواست",
  createReviewRequest: "ایجاد درخواست کارشناسی",
  createReviewRequestDescription:
    "یا فرم لینک ارسال اطلاعات برای بازدید آنلاین",
  currentCases: "پرونده‌های جاری",
  deleteTemplate: "حذف تمپلیت",
  finalCheck: "بررسی نهایی",
  linkData: "محتویات لینک",
  management: "مدیریت",
  newTemplate: "تمپلیت جدید",
  noRequestFound: "هیچ درخواستی پیدا نشد.",
  orderNumber: "شماره سفارش",
  orderNumberPlaceholder: "کد یا شماره سفارش مرجع",
  request: "درخواست‌",
  requestDetail: "مشخصات درخواست",
  requests: "درخواست‌ها",
  requestsManagement: "مدیریت درخواست‌ها",
  requestsPageDescription: "مشاهده و مدیریت لیست درخواست‌های بازدید آنلاین",
  requestSummary: "خلاصه درخواست",
  reviewType: "قالب کارشناسی",
  sendToArchive: "ارسال به بایگانی",
  specialist: 'کارشناس مسئول',
  stepsToCreateReviewLink: "مراحل ایجاد لینک کارشناسی",
  tag: 'تگ',
  templateDetails: "محتویات تمپلیت",
  templateName: "عنوان تمپلیت",
  templates: "تمپلیت‌ها",
  userAndExpertCaseInformation: "اطلاعات کاربر و مورد کارشناسی",
  userNamePlaceholder: "نام کامل، مثل بردیا جوادی",
  vehicleModel: "مدل خودرو",
  vinNumber: "شماره VIN",
  vinNumberPlaceholder: "شماره شناسایی ۱۷ رقمی خودرو",
  wantedItem: "مورد درخواستی",
  wantedItemTitle: "عنوان مورد درخواستی",
  wantedRequests: "درخواستی‌ها",
};
