export default {
  archive: "بایگانی",
  availableTemplates: "تمپلیت‌های موجود",
  branch: "نمایندگی",
  createRequest: "ایجاد درخواست",
  currentCases: "پرونده‌های جاری",
  management: "مدیریت",
  newTemplate: "تمپلیت جدید",
  noRequestFound: "هیچ درخواستی پیدا نشد.",
  orderNumber: "شماره سفارش",
  request: "درخواست‌",
  requests: "درخواست‌ها",
  requestsManagement: "مدیریت درخواست‌ها",
  requestsPageDescription: "مشاهده و مدیریت لیست درخواست‌های بازدید آنلاین",
  sendToArchive: "ارسال به بایگانی",
  templates: "تمپلیت‌ها",
  vehicleModel: "مدل خودرو",
};
