export default {
  accepted: "تایید شده",
  addedItems: "موارد اضافه شده",
  addIt: "اضافه کن",
  addNewItem: "افزودن مورد جدید",
  apolloLogo: "لوگوی آپولو",
  archived: "بایگانی شده",
  back: "بازگشت",
  bulkActions: "عملیات گروهی",
  canceled: "لغو شده",
  changeStatus: "تغییر وضعیت",
  columns: "ستون‌ها",
  continue: "ادامه",
  countPerPage: "تعداد نمایش در هر صفحه",
  create: "ایجاد",
  created: "تاریخ ایجاد",
  delete: "حذف",
  discardSelections: "لغو انتخاب شده‌ها",
  edit: "ویرایش",
  expired: "منقضی شده",
  failed: "لغو شده",
  files: "فایل‌ها",
  images: "تصاویر",
  inProgress: "در حال تکمیل",
  item: "مورد",
  nextPage: "صفحه بعد",
  opened: "باز شده",
  or: "یا",
  pending: "در انتظار بررسی",
  rejected: "رد شده",
  saveAndSubmit: "ثبت و ذخیره",
  search: "جستجو",
  selectedItemsCount: "{{selectedItems}} مورد انتخاب شده‌",
  settings: "تنظیمات",
  status: "وضعیت",
  total: "در کل",
  user: "کاربر",
};
