export default {
  accepted: "تایید شده",
  apolloLogo: "لوگوی آپولو",
  back: "بازگشت",
  bulkActions: "عملیات گروهی",
  canceled: "لغو شده",
  changeStatus: "تغییر وضعیت",
  columns: "ستون‌ها",
  continue: "ادامه",
  countPerPage: "تعداد نمایش در هر صفحه",
  create: "ایجاد",
  created: "تاریخ ایجاد",
  discardSelections: "لغو انتخاب شده‌ها",
  inProgress: "در حال تکمیل",
  or: "یا",
  pending: "در انتظار بررسی",
  search: "جستجو",
  settings: "تنظیمات",
  status: "وضعیت",
  total: "در کل",
  user: "کاربر",
};
